version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

  backend:
    build: .
    container_name: backend-api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
    volumes:
      - .:/app
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "localhost", "--port", "8000", "--reload"]
    env_file:
      - ../.env

volumes:
  postgres_data:

