version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5433:5432"  # Внешний порт 5433 → внутренний 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 2s
      retries: 30
    env_file:
      - ../.env

  backend:
    build:
      context: ..
      dockerfile: .deployment/Dockerfile
    container_name: backend-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    volumes:
      - ../:/app
    working_dir: /app
    command: sh -c "sleep 5 && python init_db.py && uvicorn main:app --host 0.0.0.0 --port 5000 --reload"
    env_file:
      - ../.env

volumes:
  postgres_data: